
(()=>{
const tools=window.WORKPAY_TOOLS;
const cards=[...document.querySelectorAll('[data-tool-card]')], input=document.getElementById('catalog-query'), suggestions=document.getElementById('search-suggestions'), noResults=document.getElementById('no-results');
let activeFilter='All';
const aliases={'time and a half':'overtime','clock in':'time card','clock out':'time card','timesheet':'time card','vacation':'pto','paid time off':'pto','promotion':'raise','yearly':'annual income','every two weeks':'biweekly','night shift':'shift differential'};
function norm(v){let q=v.toLowerCase().trim();Object.entries(aliases).forEach(([a,b])=>{if(q.includes(a))q+=' '+b});return q}
function track(event,params={}){if(typeof window.gtag==='function')window.gtag('event',event,params);window.dispatchEvent(new CustomEvent('workpay:analytics',{detail:{event,...params}}))}
function apply(){const q=norm(input.value);let shown=0;cards.forEach(c=>{const cat=c.dataset.category, text=norm(c.dataset.search);const okCat=activeFilter==='All'||cat===activeFilter;const okQ=!q||q.split(/\s+/).every(w=>text.includes(w));c.hidden=!(okCat&&okQ);if(!c.hidden)shown++});noResults.classList.toggle('show',shown===0);const status=document.getElementById('catalog-count');if(status)status.textContent=shown+' of '+tools.length+' calculators';}
input.value=new URLSearchParams(location.search).get('q')||'';apply();
function renderSuggestions(){const q=norm(input.value);if(!q){suggestions.classList.remove('open');input.setAttribute('aria-expanded','false');return}const match=tools.filter(t=>norm(t.search).includes(q)||q.split(/\s+/).some(w=>norm(t.search).includes(w))).slice(0,5);suggestions.innerHTML=match.map(t=>`<a role="option" href="/calculators/${t.slug}" data-suggest="${t.slug}"><span>${t.name}</span><small>${t.example}</small></a>`).join('');suggestions.classList.toggle('open',!!match.length);input.setAttribute('aria-expanded',String(!!match.length));}
input.addEventListener('input',()=>{apply();renderSuggestions()});document.getElementById('catalog-search').addEventListener('submit',e=>{e.preventDefault();apply();track('catalog_search',{search_term:input.value});const first=cards.find(c=>!c.hidden);if(first)first.scrollIntoView({behavior:'smooth',block:'center'})});
suggestions.addEventListener('click',e=>{const a=e.target.closest('[data-suggest]');if(a){track('catalog_search_result_click',{calculator:a.dataset.suggest});remember(a.dataset.suggest)}});
document.addEventListener('click',e=>{if(!e.target.closest('.catalog-search-wrap')){suggestions.classList.remove('open');input.setAttribute('aria-expanded','false')}});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});apply();track('catalog_filter',{filter:activeFilter})}));
document.querySelectorAll('[data-intent]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.intent;document.querySelectorAll('[data-intent]').forEach(x=>x.classList.toggle('active',x===b));activeFilter='All';document.querySelectorAll('[data-filter]').forEach((x,i)=>{x.classList.toggle('active',i===0);x.setAttribute('aria-pressed',String(i===0))});apply();document.getElementById('all-title').scrollIntoView({behavior:'smooth'});track('intent_click',{intent:b.querySelector('strong').textContent})}));
const paymap={hourly:['overtime-pay','hourly-to-salary','time-card','work-hours','weekly-pay','annual-income','shift-differential','double-time'],salary:['salary-to-hourly','pay-raise','salary-growth','contractor-salary','compensation-package','biweekly-pay','pto-value','monthly-income']};
document.querySelectorAll('[data-paytype]').forEach(b=>b.addEventListener('click',()=>{const set=new Set(paymap[b.dataset.paytype]);cards.forEach(c=>c.hidden=!set.has(c.querySelector('[data-track-tool]').dataset.trackTool));document.querySelectorAll('[data-paytype]').forEach(x=>x.classList.toggle('active',x===b));noResults.classList.remove('show');document.getElementById('catalog-count').textContent=cards.filter(c=>!c.hidden).length+' of '+tools.length+' calculators';document.getElementById('all-title').scrollIntoView({behavior:'smooth'});track('pay_type_select',{pay_type:b.dataset.paytype})}));
function remember(slug){try{let a=JSON.parse(localStorage.getItem('workpay_recent_tools')||'[]').filter(x=>x!==slug);a.unshift(slug);localStorage.setItem('workpay_recent_tools',JSON.stringify(a.slice(0,4)))}catch(e){}}
function renderRecent(){let a=[];try{a=JSON.parse(localStorage.getItem('workpay_recent_tools')||'[]')}catch(e){}const box=document.getElementById('recent-grid');box.innerHTML=a.map(s=>{const t=tools.find(x=>x.slug===s);return t?`<a class="recent-link" href="/calculators/${t.slug}" data-recent="${t.slug}">${t.name} →</a>`:''}).join('')}renderRecent();
document.querySelectorAll('[data-track-tool]').forEach(a=>a.addEventListener('click',()=>{remember(a.dataset.trackTool);track('calculator_open',{calculator:a.dataset.trackTool,source:'catalog_card'})}));document.querySelectorAll('[data-recent]').forEach(a=>a.addEventListener('click',()=>track('calculator_open',{calculator:a.dataset.recent,source:'recent'})));
document.getElementById('clear-search').addEventListener('click',()=>{input.value='';activeFilter='All';document.querySelectorAll('[data-filter]').forEach((x,i)=>{x.classList.toggle('active',i===0);x.setAttribute('aria-pressed',String(i===0))});apply();input.focus()});
input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'&&suggestions.classList.contains('open')){e.preventDefault();suggestions.querySelector('a')?.focus()}if(e.key==='Escape'){suggestions.classList.remove('open');input.setAttribute('aria-expanded','false')}});suggestions.addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const as=[...suggestions.querySelectorAll('a')],i=as.indexOf(document.activeElement),n=e.key==='ArrowDown'?Math.min(i+1,as.length-1):Math.max(i-1,0);as[n]?.focus()}if(e.key==='Escape'){suggestions.classList.remove('open');input.focus()}})
})();
