const calculators=[
 {id:'overtime',title:'Overtime Pay Calculator',short:'Overtime pay',desc:'Estimate regular, overtime, and total weekly earnings.',badge:'1.5×'},
 {id:'hourlySalary',title:'Hourly to Salary Calculator',short:'Hourly to salary',desc:'Turn an hourly wage into weekly, monthly, and annual pay.',badge:'$→Y'},
 {id:'salaryHourly',title:'Salary to Hourly Calculator',short:'Salary to hourly',desc:'Convert an annual salary into an estimated hourly rate.',badge:'Y→$'},
 {id:'raise',title:'Pay Raise Calculator',short:'Pay raise',desc:'See your new salary and added income after a raise.',badge:'%+'},
 {id:'biweekly',title:'Biweekly Pay Calculator',short:'Biweekly pay',desc:'Estimate gross pay for each of 26 paychecks per year.',badge:'26×'},
 {id:'pto',title:'PTO Value Calculator',short:'PTO value',desc:'Estimate the gross dollar value of paid time off.',badge:'PTO'}
];
const state={active:'overtime',hourly:20,regular:40,overtime:5,multiplier:1.5,weeks:52,salary:60000,raise:5,pto:80};
const usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
const field=(key,label,{prefix='',suffix='',step=1,min=0}={})=>`<label class="field"><span>${label}</span><span class="input">${prefix?`<span class="affix">${prefix}</span>`:''}<input type="number" data-key="${key}" value="${state[key]}" min="${min}" step="${step}" aria-label="${label}">${suffix?`<span class="affix">${suffix}</span>`:''}</span></label>`;
function inputs(){switch(state.active){case'overtime':return field('hourly','Hourly rate',{prefix:'$',step:.25})+`<div class="field-row">${field('regular','Regular hours',{suffix:'hrs'})}${field('overtime','Overtime hours',{suffix:'hrs'})}</div>`+field('multiplier','Overtime multiplier',{suffix:'×',step:.1,min:1});case'hourlySalary':return field('hourly','Hourly rate',{prefix:'$',step:.25})+field('regular','Hours per week',{suffix:'hrs'})+field('weeks','Paid weeks per year',{suffix:'weeks',min:1});case'salaryHourly':return field('salary','Annual salary',{prefix:'$',step:500})+field('regular','Hours per week',{suffix:'hrs',min:1})+field('weeks','Working weeks per year',{suffix:'weeks',min:1});case'raise':return field('salary','Current annual salary',{prefix:'$',step:500})+field('raise','Raise percentage',{suffix:'%',step:.1});case'biweekly':return field('salary','Annual gross salary',{prefix:'$',step:500});default:return field('pto','PTO balance',{suffix:'hours'})+field('hourly','Hourly rate',{prefix:'$',step:.25})}}
function calculate(){let headline,rows;if(state.active==='overtime'){const regular=state.hourly*state.regular,ot=state.hourly*state.multiplier*state.overtime;headline=`${usd(regular+ot)}/week`;rows=[['Regular pay',usd(regular)],['Overtime pay',usd(ot)],['Overtime rate',`${usd(state.hourly*state.multiplier)}/hr`]]}else if(state.active==='hourlySalary'){const weekly=state.hourly*state.regular,annual=weekly*state.weeks;headline=`${usd(annual)}/year`;rows=[['Weekly pay',usd(weekly)],['Monthly average',usd(annual/12)],['Annual pay',usd(annual)]]}else if(state.active==='salaryHourly'){const hourly=state.salary/Math.max(1,state.regular*state.weeks);headline=`${usd(hourly)}/hour`;rows=[['Weekly average',usd(state.salary/state.weeks)],['Monthly average',usd(state.salary/12)],['Annual salary',usd(state.salary)]]}else if(state.active==='raise'){const add=state.salary*state.raise/100;headline=`${usd(state.salary+add)}/year`;rows=[['Current salary',usd(state.salary)],['Annual increase',usd(add)],['Monthly increase',usd(add/12)]]}else if(state.active==='biweekly'){headline=`${usd(state.salary/26)}/paycheck`;rows=[['Annual gross pay',usd(state.salary)],['Monthly average',usd(state.salary/12)],['Paychecks per year','26']]}else{headline=usd(state.pto*state.hourly);rows=[['PTO hours',`${state.pto} hours`],['Hourly rate',`${usd(state.hourly)}/hr`],['Equivalent workdays',`${(state.pto/8).toFixed(1)} days`]]}document.querySelector('#headline').textContent=headline;document.querySelector('#breakdown').innerHTML=rows.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}
function render(){const current=calculators.find(c=>c.id===state.active);document.querySelector('#calculator-title').textContent=current.title;document.querySelector('#calc-description').textContent=current.desc;document.querySelector('#badge').textContent=current.badge;document.querySelector('#fields').innerHTML=inputs();document.querySelectorAll('[data-key]').forEach(input=>input.addEventListener('input',e=>{state[e.target.dataset.key]=Math.max(Number(e.target.min)||0,Number(e.target.value)||0);calculate()}));document.querySelector('#tools').innerHTML=calculators.map(c=>`<button class="tool ${c.id===state.active?'active':''}" data-id="${c.id}"><i>${c.badge}</i><span><strong>${c.short}</strong><small>${c.desc}</small></span></button>`).join('');document.querySelectorAll('.tool').forEach(button=>button.addEventListener('click',()=>{state.active=button.dataset.id;render();document.querySelector('.calculator').scrollIntoView({behavior:'smooth',block:'center'})}));calculate()}
render();
